plugins {
    id "com.android.application"
}

android {
    namespace "net.polze.adolarradio"
    compileSdk 35

    buildFeatures {
        buildConfig true
    }

    defaultConfig {
        applicationId "net.polze.adolarradio"
        minSdk 23
        targetSdk 35
        versionCode 12
        versionName "0.4.0"
    }
}

dependencies {
    implementation "androidx.media:media:1.8.0"
    implementation "androidx.media3:media3-exoplayer:1.4.1"
    implementation "androidx.media3:media3-common:1.4.1"
    implementation "androidx.media3:media3-datasource:1.4.1"
}
